name: Build React Native App with EAS

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'android'
        type: choice
        options:
          - android
          - ios
          - all
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production
  push:
    branches: [main, master]
    paths:
      - 'BuznissyMobile/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'BuznissyMobile/**'

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BuznissyMobile
    
    steps:
      - name: ðŸ“¦ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ— Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './BuznissyMobile/package-lock.json'

      - name: â˜• Setup Java 17 (for Android builds)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ðŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: ðŸ“‹ Install dependencies
        run: npm ci

      - name: ðŸ” Verify EAS configuration
        run: |
          echo "Verifying EAS configuration..."
          eas config
          echo "Project info:"
          eas project:info

      - name: ðŸ¤– Build Android App
        if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' || github.event_name == 'push' || github.event_name == 'pull_request' }}
        run: |
          echo "ðŸ¤– Building Android app..."
          PROFILE="${{ github.event.inputs.profile || 'preview' }}"
          echo "Using profile: $PROFILE"
          eas build --platform=android --profile=$PROFILE --non-interactive --wait
          echo "âœ… Android build completed"

      - name: ðŸ Build iOS App
        if: ${{ github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' }}
        run: |
          echo "ðŸ Building iOS app..."
          PROFILE="${{ github.event.inputs.profile || 'preview' }}"
          echo "Using profile: $PROFILE"
          eas build --platform=ios --profile=$PROFILE --non-interactive --wait
          echo "âœ… iOS build completed"

      - name: ðŸ“± Get Build Information
        run: |
          echo "ðŸ“± Getting build information..."
          echo "Recent builds:"
          eas build:list --platform=all --limit=5 --json > builds.json
          cat builds.json
          
          echo "Build URLs:"
          if [ "${{ github.event.inputs.platform }}" == "android" ] || [ "${{ github.event.inputs.platform }}" == "all" ] || [ "${{ github.event_name }}" == "push" ] || [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "ðŸ¤– Android APK: Check EAS dashboard for download link"
          fi
          
          if [ "${{ github.event.inputs.platform }}" == "ios" ] || [ "${{ github.event.inputs.platform }}" == "all" ]; then
            echo "ðŸ iOS IPA: Check EAS dashboard for download link"
          fi

      - name: ðŸ“Š Upload Build Artifacts Info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: ./BuznissyMobile/builds.json
          retention-days: 30

      - name: ðŸ’¬ Build Summary
        run: |
          echo "## ðŸŽ‰ Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status | Profile |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|---------|" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ github.event.inputs.platform }}" == "android" ] || [ "${{ github.event.inputs.platform }}" == "all" ] || [ "${{ github.event_name }}" == "push" ] || [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "| ðŸ¤– Android | âœ… Success | ${{ github.event.inputs.profile || 'preview' }} |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ github.event.inputs.platform }}" == "ios" ] || [ "${{ github.event.inputs.platform }}" == "all" ]; then
            echo "| ðŸ iOS | âœ… Success | ${{ github.event.inputs.profile || 'preview' }} |" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ“± **Download your app from the [EAS Dashboard](https://expo.dev/accounts/buznissy/projects/buznissy/builds)**" >> $GITHUB_STEP_SUMMARY
